declare const process: {
  env: {
    EXPO_PUBLIC_PERSIST_NAVIGATION: boolean;
    EXPO_PUBLIC_CATCH_ERRORS: boolean;
    EXPO_PUBLIC_API_URL: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: string;
    EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID: string;
    EXPO_PUBLIC_MMKV_ENCRYPTION_KEY: string;
    EXPO_PUBLIC_CODEPUSH_DEPLOYMENT_KEY_IOS: string;
    EXPO_PUBLIC_CODEPUSH_DEPLOYMENT_KEY_ANDROID: string;
  };
};
